### PR TITLE
V0.1.8

### PR DESCRIPTION
**Pull request by pioneerit**
- Remove cloning resource attributes from prior resource (CHEF-3694)
- Permanent fix for [#8](https://github.com/vkhatri/chef-aerospike-cluster/issues/8) - remote_file for enterprise edition with authentication
- After PR [#12](https://github.com/vkhatri/chef-aerospike-cluster/pull/12) attribute `mesh-seed-address-port` not needed.
- Update cluster.rb recipe for default value and support chef-solo if possible
- Restart `amc` applicatoin if `aerospike` was restarted
- Update tests and rake's tasks

### CODE REVIEW

**Comment by vkhatri** [comment]
@pioneerit LGTM, Could you please rebase the PR?

**Comment by pioneerit** [comment]
Yeap, 5 min

**Comment by pioneerit** [comment]
GitHub says there is nothing to rebase. I think because this both version in a row from me

**Comment by pioneerit** [comment]
@vkhatri, sorry. It's 8 P.M., a little bit tired.
I've rebased via CLI.

**Comment by pioneerit** [comment]
I've left version bump to the last commit. And as I've started working on a new version again :), I found that I forgot to bump previous.

**Comment by pioneerit** [comment]
Newer version PR #23

**Pull request closed without merging**
